/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	samplev1 "github.com/kamiazya/k8s-cdr-custom-controller-playground/pkg/apis/sample/v1"
	versioned "github.com/kamiazya/k8s-cdr-custom-controller-playground/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kamiazya/k8s-cdr-custom-controller-playground/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/kamiazya/k8s-cdr-custom-controller-playground/pkg/client/listers/sample/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HogeInformer provides access to a shared informer and lister for
// Hoges.
type HogeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.HogeLister
}

type hogeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHogeInformer constructs a new informer for Hoge type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHogeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHogeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHogeInformer constructs a new informer for Hoge type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHogeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SampleV1().Hoges(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SampleV1().Hoges(namespace).Watch(options)
			},
		},
		&samplev1.Hoge{},
		resyncPeriod,
		indexers,
	)
}

func (f *hogeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHogeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hogeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&samplev1.Hoge{}, f.defaultInformer)
}

func (f *hogeInformer) Lister() v1.HogeLister {
	return v1.NewHogeLister(f.Informer().GetIndexer())
}
