/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/kamiazya/k8s-cdr-custom-controller-playground/pkg/apis/sample/v1"
	scheme "github.com/kamiazya/k8s-cdr-custom-controller-playground/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HogesGetter has a method to return a HogeInterface.
// A group's client should implement this interface.
type HogesGetter interface {
	Hoges(namespace string) HogeInterface
}

// HogeInterface has methods to work with Hoge resources.
type HogeInterface interface {
	Create(*v1.Hoge) (*v1.Hoge, error)
	Update(*v1.Hoge) (*v1.Hoge, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Hoge, error)
	List(opts metav1.ListOptions) (*v1.HogeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Hoge, err error)
	HogeExpansion
}

// hoges implements HogeInterface
type hoges struct {
	client rest.Interface
	ns     string
}

// newHoges returns a Hoges
func newHoges(c *SampleV1Client, namespace string) *hoges {
	return &hoges{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hoge, and returns the corresponding hoge object, and an error if there is any.
func (c *hoges) Get(name string, options metav1.GetOptions) (result *v1.Hoge, err error) {
	result = &v1.Hoge{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hoges").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Hoges that match those selectors.
func (c *hoges) List(opts metav1.ListOptions) (result *v1.HogeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.HogeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hoges").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hoges.
func (c *hoges) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hoges").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hoge and creates it.  Returns the server's representation of the hoge, and an error, if there is any.
func (c *hoges) Create(hoge *v1.Hoge) (result *v1.Hoge, err error) {
	result = &v1.Hoge{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hoges").
		Body(hoge).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hoge and updates it. Returns the server's representation of the hoge, and an error, if there is any.
func (c *hoges) Update(hoge *v1.Hoge) (result *v1.Hoge, err error) {
	result = &v1.Hoge{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hoges").
		Name(hoge.Name).
		Body(hoge).
		Do().
		Into(result)
	return
}

// Delete takes name of the hoge and deletes it. Returns an error if one occurs.
func (c *hoges) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hoges").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hoges) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hoges").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hoge.
func (c *hoges) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Hoge, err error) {
	result = &v1.Hoge{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hoges").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
